---
    - block:
      - name: Install Oracle Java 8 repository
        apt_repository: repo='ppa:webupd8team/java'

      - name: Accept Java 8 License
        debconf: >
          name='oracle-java8-installer'
          question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

      - name: Install Oracle Java 8
        apt: name=oracle-java8-installer update_cache=yes  state=present force=yes
